config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  namespace :admins do
    root :to => 'dashboard#index'
    get "account/change_password" => "accounts#change_password", :as => :change_password
    put "account/update_password" => "accounts#update_password", :as => :update_password

    resources :articles do
      member do
        delete "delete_attachment/:asset_id" => "articles#delete_attachment", :as => :delete_attachment
        delete "delete_attachment_image/:asset_id" => "articles#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :categories
    resources :questions
    resources :specialists
    resources :testimonials
    resources :contacts
    resources :facilities do
      member do
        delete "delete_attachment_image/:asset_id/field/:field" => "facilities#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :doctors do
      resources :schedules, :controller => "doctors/schedules", :except => [:index, :show]
      member do
        delete "delete_attachment_image/:asset_id" => "doctors#delete_attachment_image", :as => :delete_attachment_image
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # i18n Scope for id
  resource :contact, :only => [:show, :create]

  match 'about', to: 'home#about', via: :get, as: :about
  match 'treatments', to: 'home#treatments', via: :get, as: :treatments
  match '/practitioners', to: 'doctors#index', via: :get, as: :practitioners
  match '/practitioners/:id', to: 'doctors#show', via: :get, as: :practitioner
  match '/journals', to: 'articles#index', via: :get, as: :journals
  match '/journals/:id', to: 'articles#show', via: :get, as: :journal

  root :to => "home#index"
end

app/models/category.rb
class Category < ApplicationRecord

	default_scope { order(id: :asc) }

	validates_presence_of :name
	validates_uniqueness_of :name

	has_many :articles

end

app/controllers/admins/categories_controller.rb
class Admins::CategoriesController < Admins::BaseController
	before_action :set_category, except: [:index, :new, :create]

  def index
    criteria = Category.all
    @categories = criteria.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @categories }
      format.js
    end
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(params_category)
    if @category.save
			redirect_to admins_category_path(@category.id), :notice => "Successfully created category."
    else
      render :action => 'new'
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
			redirect_to admins_category_path(@category.id), :notice  => "Successfully updated category."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @category.destroy
    redirect_to admins_categories_url, :notice => "Successfully destroyed category."
  end

  private

  def params_category
    params.require(:category).permit(:name)
  end

	def set_category
		@category = Category.find(params[:id])
	end
end

app/views/admins/categories/_form.html.erb
<%= simple_form_for @category, url: (@category.new_record? ? admins_categories_path : admins_category_path(@category.id)), method: (@category.new_record? ? :post : :put) do |f| %>
	<%= f.error_notification %>
	<fieldset>
		<%= f.input :name, as: :string %>
	</fieldset>
	<%= f.error :base %>
	<div class="form-actions">
		<%= f.button :submit, :class => 'btn btn-secondary' %>
		<% unless @category.new_record? %>
			<%= link_to "Cancel", admins_category_path(@category.id), :class => 'btn btn-light' %>
		<% else %>
			<%= link_to "Cancel", admins_categories_path, :class => 'btn btn-light' %>
		<% end %>
	</div>
<% end %>

app/views/admins/categories/_table.html.erb
<div class="table-card">
	<table class="table table-hover table-striped align-middle mb-0">
		<thead class="table-light">
			<tr>
				<th class="text-center" style="width:10%;">ID</th>
				<th>Name</th>
				<th class="text-center">Articles</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% for category in @categories %>
				<tr>
					<td class="text-center"><%= category.id %></td>
					<td><h5 class="fs-14 mb-0"><%= link_to category.name, admins_category_path(category.id), class: "text-body" %></h5></td>
					<td class="text-center"><%= category.articles.size %></td>
					<td>
						<div class="dropdown">
							<button class="btn btn-soft-secondary btn-sm dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="ri-more-fill"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-end">
								<li>
									<%= link_to admins_category_path(category.id), class: "dropdown-item" do %>
										<i class="ri-eye-fill align-bottom me-2 text-muted"></i> View
									<% end %>
								</li>
								<li>
									<%= link_to edit_admins_category_path(category.id), class: "dropdown-item edit-list" do %>
										<i class="ri-pencil-fill align-bottom me-2 text-muted"></i> Edit
									<% end %>
								</li>
								<li class="dropdown-divider"></li>
								<li>
									<%= link_to admins_category_path(category.id), :data => { :confirm => 'Are you sure?' }, :method => :delete, class: "dropdown-item remove-list" do %>
										<i class="ri-delete-bin-fill align-bottom me-2 text-muted"></i> Delete
									<% end %>
								</li>
							</ul>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<!-- pagination -->
<%= paginate @categories %>

app/views/admins/categories/edit.html.erb
<% title_page("Edit Category") %>
<div class="row">
	<div class="col-lg-8">
		<div class="card">
			<div class="card-body">
				<%= render "form" %>
			</div>
		</div>
	</div>
	<%= render "admins/shared/error_messages", :target => @category %>
</div>

app/views/admins/categories/index.html.erb
<% title_page("Categories") %>
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header border-0">
				<div class="row g-4 align-items-center">
					<div class="col-sm-auto ms-auto">
						<div class="hstack gap-2">
							<a class="btn btn-success add-btn" href="<%= new_admins_category_path %>"><i class="ri-add-line align-bottom me-1"></i> Add Category</a>
						</div>
					</div>
				</div>
			</div>
			<div class="card-body">
				<%= render 'table' %>
			</div>
		</div>
	</div>
	<!--end col-->
</div>
<!--end row-->

app/views/admins/categories/index.js.erb
$("#index_table").html("<%= escape_javascript(render("table")) %>");

app/views/admins/categories/new.html.erb
<% title_page("Create New Category") %>
<div class="row">
	<div class="col-lg-8">
		<div class="card">
			<div class="card-body">
				<%= render "form" %>
			</div>
		</div>
	</div>
	<%= render "admins/shared/error_messages", :target => @category %>
</div>

app/views/admins/categories/show.html.erb
<% title_page("Category details") %>
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<table class="table table-hover">
					<tr>
						<td style="width:10%;"><b>ID</b></td>
						<td><%= @category.id %></td>
					</tr>
					<tr>
						<td><b>Name</b></td>
						<td><h5 class="fs-14 mb-0 text-body"><%= @category.name %></h5></td>
					</tr>
					<tr>
						<td><b>Articles</b></td>
						<td><%= @category.articles.size %></td>
					</tr>
				</table>
				<div class="form-actions">
					<%= link_to 'Edit', edit_admins_category_path(@category.id), :class => 'btn btn-secondary' %>
					<%= link_to 'Destroy', admins_category_path(@category.id), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-danger' %>
					<%= link_to 'View All', admins_categories_path, :class => 'btn btn-light' %>
				</div>
			</div>
		</div>
	</div>
</div>