config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  namespace :admins do
    root :to => 'dashboard#index'
    get "account/change_password" => "accounts#change_password", :as => :change_password
    put "account/update_password" => "accounts#update_password", :as => :update_password

    resources :articles do
      member do
        delete "delete_attachment/:asset_id" => "articles#delete_attachment", :as => :delete_attachment
        delete "delete_attachment_image/:asset_id" => "articles#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :categories
    resources :questions
    resources :specialists
    resources :testimonials
    resources :contacts
    resources :facilities do
      member do
        delete "delete_attachment_image/:asset_id/field/:field" => "facilities#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :doctors do
      resources :schedules, :controller => "doctors/schedules", :except => [:index, :show]
      member do
        delete "delete_attachment_image/:asset_id" => "doctors#delete_attachment_image", :as => :delete_attachment_image
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # i18n Scope for id
  resource :contact, :only => [:show, :create]

  match 'about', to: 'home#about', via: :get, as: :about
  match 'treatments', to: 'home#treatments', via: :get, as: :treatments
  match '/practitioners', to: 'doctors#index', via: :get, as: :practitioners
  match '/practitioners/:id', to: 'doctors#show', via: :get, as: :practitioner
  match '/journals', to: 'articles#index', via: :get, as: :journals
  match '/journals/:id', to: 'articles#show', via: :get, as: :journal

  root :to => "home#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord

	extend FriendlyId
  friendly_id :full_name, use: :slugged

	default_scope { order(id: :asc) }

	validates_presence_of :full_name, :profesional_name, :email, :phone
	validates_uniqueness_of :email, :full_name
	validates :photo, content_type: ['image/png', 'image/jpeg']

	has_many :specialities
  has_many :specialists, :through => :specialities
	has_many :appointments
	has_many :schedules, dependent: :destroy

	has_one_attached :photo, dependent: :purge
  has_rich_text :content

	def operational_hours_label
		strLabel = ""
		self.schedules.each do |s|
			strLabel += "#{s.day_name}: #{s.start_time} - #{s.end_time}<br/>"
		end

		return strLabel
	end

	def should_generate_new_friendly_id?
		self.full_name_changed?
	end

	def find_other_doctors(_limit)
		Doctor.where.not(id: self.id).limit(_limit)
	end

	def profesional_name_with_title
		"#{self.profesional_name} (#{self.title})"
	end

end

app/models/schedule.rb
class Schedule < ApplicationRecord

	default_scope { order(day_code: :asc) }

	belongs_to :doctor

	validates_presence_of :day_name, :day_code

	before_validation :set_day_name

	def set_day_name
		self.day_name = Date::DAYNAMES[self.day_code]
	end

	def get_session_time
		"#{self.start_time} - #{self.end_time}"
	end

end

app/controllers/admins/doctors/schedules_controller.rb
class Admins::Doctors::SchedulesController < Admins::BaseController
	before_action :set_doctor

	def new
		@schedule = @doctor.schedules.build

    respond_to do |format|
      format.js { render :action => :form }
    end
	end

  def create
		@success = false
		@schedule = @doctor.schedules.build(params_schedule)
    if @schedule.save
      flash[:notice] = "Successfully add schedule"
			@success = true
			set_schedules
    end

    respond_to do |format|
      format.js { render :action => (@success == true ? :update : :form) }
    end
  end

	def edit
		@schedule = @doctor.schedules.find(params[:id])

    respond_to do |format|
      format.js { render :action => :form }
    end
	end

  def update
		@success = false
		@schedule = @doctor.schedules.find(params[:id])
    if @schedule.update(params_schedule)
      flash[:notice] = "Successfully update schedule"
			@success = true
    end

    respond_to do |format|
      format.js { render :action => (@success == true ? :update : :form) }
    end
  end

  def destroy
		@schedule = @doctor.schedules.find(params[:id])
		@schedule.destroy
		set_schedules
		flash[:notice] = "Schedule deleted."

    respond_to do |format|
      format.js { render :action => :update }
    end
  end

  private

  def params_schedule
		params.require(:schedule).permit(:day_code, :start_time, :end_time)
  end

	def set_doctor
		@doctor = Doctor.find(params[:doctor_id])
	end

	def set_schedules
		@schedules = @doctor.schedules
	end

end

app/controllers/admins/doctors_controller.rb
class Admins::DoctorsController < Admins::BaseController
	before_action :set_doctor, except: [:index, :new, :create]

  def index
		criteria = Doctor.where("full_name ILIKE ?", "%#{params[:search]}%")

    @doctors = criteria.page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @doctors }
      format.js
    end
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(params_doctor)
    if @doctor.save
			redirect_to admins_doctor_path(@doctor.id), :notice => "Successfully created doctor."
    else
      render :action => 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @doctor.update(params_doctor)
			redirect_to admins_doctor_path(@doctor.id), :notice  => "Successfully updated doctor."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @doctor.destroy
    redirect_to admins_doctors_url, :notice => "Successfully destroyed doctor."
  end

	def delete_attachment_image
		if @asset = ActiveStorage::Attachment.find(params[:asset_id])
			flash[:notice] = "Successfully delete image."
			@doctor.photo.purge
		end
		redirect_to admins_doctor_path(@doctor.id)
	end

  private

  def params_doctor
    params.require(:doctor).permit(:email, :str_no, :profesional_name, :full_name, :title, :phone, :alumni, :photo, :content, specialist_ids: [])
  end

  def set_doctor
		@doctor = Doctor.find(params[:id])
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController

  def index
		unless params[:search]
			criteria = Doctor.all
		else
			criteria = Specialist.where("professional_name LIKE ? or full_name LIKE ? or title LIKE ?", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
		end
    @doctors = criteria.page(params[:page]).per(12)

    respond_to do |format|
      format.html # index.html.erb
      format.js
    end
  end

  def show
		@doctor = Doctor.friendly.find(params[:id])
		# Other Doctors
		@doctors = []
		if @doctor
			@doctors = @doctor.find_other_doctors(3)
		end
  end

end

app/views/admins/doctors/schedules/_form.html.erb
<div class="modal-header">
	<h5 class="modal-title">Doctor schedule</h5>
	<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
<%= simple_form_for @schedule, url: (@schedule.new_record? ? admins_doctor_schedules_path(@doctor.id) : admins_doctor_schedule_path(@doctor.id, @schedule.id)), method: (@schedule.new_record? ? :post : :put), remote: true do |f| %>
	<%= f.error_notification %>
	<%= f.input :day_code, as: :select, collection: Date::DAYNAMES.each_with_index.map { |x, i| [x, i] }, include_blank: false %>
	<%= f.input :start_time, as: :select, collection: populate_array_of_time, include_blank: true %>
	<%= f.input :end_time, as: :select, collection: populate_array_of_time, include_blank: true %>
	<div class="row">
		<div class="col-lg-12">
			<div class="hstack gap-2 justify-content-end">
				<a class="btn btn-light" data-bs-dismiss="modal" aria-label="Close">Close</a>
				<%= f.button :submit, 'Save', :class => 'btn btn-secondary' %>
			</div>
		</div>
	</div>
<% end %>
</div>

app/views/admins/doctors/schedules/_table.html.erb
<div class="table-card">
	<table class="table align-middle">
		<thead class="table-light">
			<tr>
				<th class="text-center">Day</th>
				<th>Start Time</th>
				<th>End Time</th>
				<th class="text-center">Action</th>
			</tr>
		</thead>
		<tbody>
			<% for s in @doctor.schedules %>
				<tr>
					<td class="text-center"><b><%= s.day_name %></b></td>
					<td><%= s.start_time %></td>
					<td><%= s.end_time %></td>
					<td class="text-center">
						<div class="dropdown">
							<button class="btn btn-soft-secondary btn-sm dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="ri-more-fill"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-end">
								<li>
									<%= link_to edit_admins_doctor_schedule_path(@doctor.id, s), :remote => true, class: "dropdown-item edit-list" do %>
										<i class="ri-pencil-fill align-bottom me-2 text-muted"></i> Edit
									<% end %>
								</li>
								<li class="dropdown-divider"></li>
								<li>
									<%= link_to admins_doctor_schedule_path(@doctor.id, s), :data => { :confirm => 'Are you sure?' }, :method => :delete, :remote => true, class: "dropdown-item remove-list" do %>
										<i class="ri-delete-bin-fill align-bottom me-2 text-muted"></i> Delete
									<% end %>
								</li>
							</ul>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/admins/doctors/schedules/form.js.erb
$("#myModal .modal-content").html("<%= escape_javascript(render("form")) %>");
$("#myModal").modal('show');

app/views/admins/doctors/schedules/update.js.erb
$("#doctorSchedulesTable").html("<%= escape_javascript(render("table")) %>");
$("#forFlashMessage").html("<%= escape_javascript(flash_message) %>");
<% if @success == true %>
	$("#myModal .modal-content").html("<%= escape_javascript(render("form")) %>");
	$("#myModal").modal('hide');
<% end %>
<%- flash.discard -%>