config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  namespace :admins do
    root :to => 'dashboard#index'
    get "account/change_password" => "accounts#change_password", :as => :change_password
    put "account/update_password" => "accounts#update_password", :as => :update_password

    resources :articles do
      member do
        delete "delete_attachment/:asset_id" => "articles#delete_attachment", :as => :delete_attachment
        delete "delete_attachment_image/:asset_id" => "articles#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :categories
    resources :questions
    resources :specialists
    resources :testimonials
    resources :contacts
    resources :facilities do
      member do
        delete "delete_attachment_image/:asset_id/field/:field" => "facilities#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :doctors do
      resources :schedules, :controller => "doctors/schedules", :except => [:index, :show]
      member do
        delete "delete_attachment_image/:asset_id" => "doctors#delete_attachment_image", :as => :delete_attachment_image
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # i18n Scope for id
  resource :contact, :only => [:show, :create]

  match 'about', to: 'home#about', via: :get, as: :about
  match 'treatments', to: 'home#treatments', via: :get, as: :treatments
  match '/practitioners', to: 'doctors#index', via: :get, as: :practitioners
  match '/practitioners/:id', to: 'doctors#show', via: :get, as: :practitioner
  match '/journals', to: 'articles#index', via: :get, as: :journals
  match '/journals/:id', to: 'articles#show', via: :get, as: :journal

  root :to => "home#index"
end

app/views/shared/_appointment.html.erb
<section class="half-section parallax wow animate__fadeIn"  data-parallax-background-ratio="0.3" style="background-image: url('<%= image_url('colorful-humidity-glass.png') %>');">
    <div class="container position-relative">
        <div class="row">
            <div class="col-12 text-center d-flex align-items-center justify-content-center">
              <a href="#" class="btn btn-double-extra-large btn-transparent-white text-large text-uppercase d-table d-lg-inline-block md-margin-lr-auto">
                <img src="<%= image_url('logo-icon2.png') %>" class="w-50px sm-w-30px" />
                Book Appointment
                <img src="<%= image_url('logo-icon2.png') %>" class="w-50px sm-w-30px" />
              </a>
            </div>
        </div>
    </div>
</section>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
<div class="sidebox widget">
  <h3><%= pluralize(target.errors.count, "error") + " prohibited this record from being saved:" %></h3>
  <ul class="list circled" style="color:#d6253a;">
    <% target.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%= render "shared/appointment" %>
<!-- start footer -->
<footer class="footer-standard cover-background footer-bg">
    <div class="footer-widget-area padding-three-tb sm-padding-30px-tb">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6 widget md-margin-30px-bottom text-center text-sm-start">
                    <!-- start logo -->
                    <%= link_to root_path, class: "margin-20px-bottom d-inline-block" do %>
                      <%= image_tag('logo-black.png', class: "footer-logo") %>
                    <% end %>
                    <!-- end logo -->
                    <p class="d-inline-block w-70 lg-w-70 sm-w-95 xs-w-95">Kalyce aims to create a serene, sophisticated environment where individuals can experience advanced, personalized aesthetic treatments that promote both inner and outer well-being.</p>
                </div>
                <!-- start additional links -->
                <div class="col-6 col-md-3 widget d-none d-md-block padding-45px-left md-padding-15px-left md-margin-30px-bottom link-style-2">
                    <div class="widget-title alt-font text-extra-dark-gray text-uppercase margin-20px-bottom font-weight-600">Menu</div>
                    <ul class="text-double-extra-large list-unstyled">
                      <li><a href="<%= root_url %>">Home</a></li>
                      <li><a href="<%= about_url %>">About</a></li>
                      <li><a href="<%= treatments_url %>">Treatments</a></li>
                      <li><a href="<%= practitioners_url %>">Practitioners</a></li>
                      <li><a href="<%= journals_url %>">Journal</a></li>
                      <li><a href="<%= contact_url %>">Contact</a></li>
                    </ul>
                </div>
                <!-- end additional links -->
                <!-- start contact information -->
                <div class="col-12 col-md-3 widget text-center text-md-start padding-45px-left md-padding-15px-left xs-margin-30px-bottom link-style-2">
                    <div class="widget-title alt-font text-extra-dark-gray text-uppercase margin-20px-bottom font-weight-600">Contact</div>
                    <p class="text-medium d-inline-block d-md-block margin-25px-bottom"><%= raw configatron.company_address %></p>
                    <div class="margin-10px-bottom">T: <%= configatron.company_phone %></div>
                    <div class="margin-20px-bottom">E: <a href="mailto:<%= configatron.company_email %>" class="text-deep-pink-hover"><%= configatron.company_email %></a></div>
                    <!-- start social media -->
                    <div class="social-icon-style-8 d-inline-block align-middle">
                        <ul class="medium-icon mb-0">
                          <li><a href="<%= configatron.social_facebook_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-facebook-f" aria-hidden="true"></i></a></li>
                          <li><a href="<%= configatron.social_linkedin_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-linkedin" aria-hidden="true"></i></a></li>
                          <li><a href="<%= configatron.social_instagram_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-instagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                    <!-- end social media -->
                </div>
                <!-- end contact information -->
            </div>
        </div>
    </div>
</footer>
<!-- end footer -->

app/views/shared/_header.html.erb
<!-- start header -->
<header class="no-sticky">
    <!-- start navigation -->
    <nav class="navbar full-width-pull-menu navbar-top-scroll no-border-top nav-box-width white-link no-transition">
        <!-- start navigation panel -->
        <div class="container-fluid nav-header-container h-100px sm-h-70px">
            <!-- start logo -->
            <div class="col-auto ps-0">
              <%= link_to root_path, title: "Kalyce", class: "logo" do %>
                <%= image_tag("logo-white.png", alt: "Kalyce") %>
              <% end %>
            </div>
            <!-- end logo -->
            <!-- start main menu -->
            <div class="col-auto pe-0">
                <div class="menu-wrap full-screen">
                    <div class="row g-0 h-100 justify-content-center">
                        <div class="col-md-5 p-0 text-center z-index-0 d-none d-md-flex flex-column justify-content-center">
                            <div class="z-index-minus1 opacity-medium bg-extra-dark-gray"></div>
                            <%= link_to root_path, title: "Kalyce" do %>
                              <%= image_tag("logo-white.png", alt: "Kalyce") %>
                            <% end %>
                        </div>
                        <div id="parentMenuKalyce" class="col-md-7 px-0 full-screen d-flex flex-column justify-content-center xs-padding-45px-tb cover-background <%= set_bg_menu %>">
                            <div class="w-100 overflow-auto">
                                <div class="h-100 w-100">
                                    <div class="h-100 w-100 overflow-hidden align-middle text-center text-md-end padding-six-lr alt-font link-style-2 lg-padding-six-lr xs-padding-15px-lr">
                                        <div class="d-block d-md-none">
                                          <%= link_to root_path, title: "Kalyce" do %>
                                            <%= image_tag("logo-black.png", class: "w-180px", alt: "Kalyce") %>
                                          <% end %>
                                        </div>
                                        <!-- start menu -->
                                        <ul class="font-weight-400 no-padding-left mt-0 mb-0">
                                          <li class="home"><a class="<%= 'active' if is_home_page? %>" href="<%= root_url %>">Home</a></li>
                                          <li class="about"><a class="<%= 'active' if is_about_page? %>" href="<%= about_url %>">About</a></li>
                                          <li class="treatments"><a class="<%= 'active' if is_treatments_page? %>" href="<%= treatments_url %>">Treatments</a></li>
                                          <li class="practitioners"><a class="<%= 'active' if is_practitioners_page? %>" href="<%= practitioners_url %>">Practitioners</a></li>
                                          <li class="journals"><a class="<%= 'active' if is_journals_page? %>" href="<%= journals_url %>">Journal</a></li>
                                          <li class="contact"><a class="<%= 'active' if is_contact_page? %>" href="<%= contact_url %>">Contact</a></li>
                                        </ul>
                                        <!-- end menu -->
                                        <!-- start social links -->
                                        <div class="margin-seven-top">
                                            <div class="icon-social-large">
                                              <a href="<%= configatron.social_facebook_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-facebook-f" aria-hidden="true"></i></a>
                                              <a href="<%= configatron.social_linkedin_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-linkedin" aria-hidden="true"></i></a>
                                              <a href="<%= configatron.social_instagram_url %>" target="_blank" class="text-extra-dark-gray text-deep-pink-hover margin-one-lr"><i class="fa-brands fa-instagram" aria-hidden="true"></i></a>
                                            </div>
                                        </div>
                                        <!-- start social links -->
                                    </div>
                                </div>
                            </div>
                            <button class="close-button-menu" id="close-button"></button>
                        </div>
                    </div>
                </div>
                <!-- end main menu -->
                <button class="navbar-toggler mobile-toggle" type="button" id="open-button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse">
                    <span></span>
                    <span></span>
                    <span></span>
                </button>
            </div>
        </div>
        <!-- end navigation panel -->
    </nav>
    <!-- end navigation -->
</header>
<!-- end header -->

app/views/shared/_small_banner.html.erb
<!-- start page title section -->
<section class="big-section pb-5 wow animate__fadeIn cover-background background-position-top page-title-small top-space" style="background-image:url('<%= image_url('banners/banner-small.png') %>');">
    <div class="opacity-extra-medium bg-black"></div>
    <div class="container-fluid margin-four-lr sm-no-margin-lr">
        <div class="row align-items-center">
            <div class="col-12 col-md-12 position-relative alt-font breadcrumb justify-content-center justify-content-md-start text-large">
                <!-- start breadcrumb -->
                <ul>
                  <li><a href="<%= root_path %>" class="text-white-2">Home</a></li>
                  <li><a href="<%= parent_path %>" class="text-white-2"><%= parent_text %></a></li>
                  <li class="text-white-2"><%= title %></li>
                </ul>
                <!-- end breadcrumb -->
            </div>
        </div>
    </div>
</section>
<!-- end page title section -->