config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  #get "up" => "rails/health#show", as: :rails_health_check

  devise_for :admins, :controllers => { :sessions => "admins/sessions" }

  namespace :admins do
    root :to => 'dashboard#index'
    get "account/change_password" => "accounts#change_password", :as => :change_password
    put "account/update_password" => "accounts#update_password", :as => :update_password

    resources :articles do
      member do
        delete "delete_attachment/:asset_id" => "articles#delete_attachment", :as => :delete_attachment
        delete "delete_attachment_image/:asset_id" => "articles#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :categories
    resources :questions
    resources :specialists
    resources :testimonials
    resources :contacts
    resources :facilities do
      member do
        delete "delete_attachment_image/:asset_id/field/:field" => "facilities#delete_attachment_image", :as => :delete_attachment_image
      end
    end
    resources :doctors do
      resources :schedules, :controller => "doctors/schedules", :except => [:index, :show]
      member do
        delete "delete_attachment_image/:asset_id" => "doctors#delete_attachment_image", :as => :delete_attachment_image
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # i18n Scope for id
  resource :contact, :only => [:show, :create]

  match 'about', to: 'home#about', via: :get, as: :about
  match 'treatments', to: 'home#treatments', via: :get, as: :treatments
  match '/practitioners', to: 'doctors#index', via: :get, as: :practitioners
  match '/practitioners/:id', to: 'doctors#show', via: :get, as: :practitioner
  match '/journals', to: 'articles#index', via: :get, as: :journals
  match '/journals/:id', to: 'articles#show', via: :get, as: :journal

  root :to => "home#index"
end

app/views/admins/admins/_form.html.erb
<%= simple_form_for [:admins, @admin] do |f| %>
	<%= f.error_notification %>
	<fieldset>
		<%= f.input :full_name %>
		<%= f.input :email %>
		<%= f.association :role, as: :select %>
		<%= f.input :password %>
		<%= f.input :password_confirmation %>
	</fieldset>
	<%= f.error :base %>
	<div class="form-actions">
		<%= f.button :submit, :class => 'btn btn-secondary' %>
		<%= link_to "Cancel", admins_admins_path, :class => 'btn btn-light' %>
	</div>
<% end %>

app/views/admins/admins/_table.html.erb
<div class="table-card">
	<table class="table table-hover table-striped align-middle mb-0">
		<thead class="table-light">
			<tr>
				<th class="text-center">ID</th>
				<th>Full Name</th>
				<th>Email</th>
				<th>Role</th>
				<th>Last Sign In</th>
				<th>Created At</th>
				<th>Action</th>
			</tr>
		</thead>
		<tbody>
			<% for admin in @admins %>
				<tr>
					<td class="text-center"><%= admin.id %></td>
					<td><h5 class="fs-14"><%= link_to admin.full_name, admins_admin_path(admin), class: "text-body" %></h5></td>
					<td><%= admin.email %></td>
					<td><%= admin.role.name %></td>
					<td><%= admin.try(:last_sign_in_at).try(:strftime,'%d/%m/%Y %H:%M') %></td>
					<td><%= admin.created_at.strftime('%d/%m/%Y %H:%M') %></td>
					<td>
						<div class="dropdown">
							<button class="btn btn-soft-secondary btn-sm dropdown" type="button" data-bs-toggle="dropdown" aria-expanded="false">
								<i class="ri-more-fill"></i>
							</button>
							<ul class="dropdown-menu dropdown-menu-end">
								<li>
									<%= link_to admins_admin_path(admin), class: "dropdown-item" do %>
										<i class="ri-eye-fill align-bottom me-2 text-muted"></i> View
									<% end %>
								</li>
								<li class="dropdown-divider"></li>
								<li>
									<%= link_to admins_admin_path(admin), :data => { :confirm => 'Are you sure?' }, :method => :delete, class: "dropdown-item remove-list" do %>
										<i class="ri-delete-bin-fill align-bottom me-2 text-muted"></i> Delete
									<% end %>
								</li>
							</ul>
						</div>
					</td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>
<!-- pagination -->
<%= paginate @admins %>

app/views/admins/admins/edit.html.erb
<% title_page("Edit Admin") %>
<div class="row">
	<div class="col-lg-8">
		<div class="card">
			<div class="card-body">
				<%= render "form" %>
			</div>
		</div>
	</div>
	<%= render "admins/shared/error_messages", :target => @admin %>
</div>

app/views/admins/admins/index.html.erb
<% title_page("Admins") %>
<div class="row">
	<div class="col-lg-12">
		<div class="card">
			<div class="card-header border-0">
				<div class="row g-4 align-items-center">
					<div class="col-md-4">
						<%= form_tag admins_admins_url, { :id => "index_search", :method => :get } do %>
							<div class="form-icon">
								<%= text_field_tag :search, params[:search], :class => "form-control form-control-icon", :placeholder => "Search administrator" %>
								<i class="ri-search-line"></i>
							</div>
						<% end %>
					</div>
					<div class="col-sm-auto ms-auto">
						<div class="hstack gap-2">
							<a class="btn btn-success add-btn" href="<%= new_admins_admin_path %>"><i class="ri-add-line align-bottom me-1"></i> Add Admin</a>
						</div>
					</div>
				</div>
			</div>
			<div id="index_table" class="card-body">
				<%= render 'table' %>
			</div>
		</div>
	</div>
	<!--end col-->
</div>
<!--end row-->

app/views/admins/admins/index.js.erb
$("#index_table").html("<%= escape_javascript(render("table")) %>");

app/views/admins/admins/new.html.erb
<% title_page("Create New Admin") %>
<div class="row">
	<div class="col-lg-8">
		<div class="card">
			<div class="card-body">
				<%= render "form" %>
			</div>
		</div>
	</div>
	<%= render "admins/shared/error_messages", :target => @admin %>
</div>

app/views/admins/admins/show.html.erb
<% title_page("Admin details") %>
<div class="row">
	<div class="col-12">
		<div class="card">
			<div class="card-body">
				<table class="table table-hover">
					<tr>
						<td style="width:20%;"><b>ID</b></td>
						<td><%= @admin.id %></td>
					</tr>
					<tr>
						<td><b>Full Name</b></td>
						<td><h5 class="fs-14 mb-0 text-body"><%= @admin.full_name %></h5></td>
					</tr>
					<tr>
						<td><b>Email</b></td>
						<td><%= @admin.email %></td>
					</tr>
					<tr>
						<td><b>Password</b></td>
						<td>*****</td>
					</tr>
					<tr>
						<td><b>Role</b></td>
						<td><%= @admin.role.name %></td>
					</tr>
					<tr>
						<td><b>Last Sign In At</b></td>
						<td><%= @admin.try(:last_sign_in_at).try(:strftime, '%d/%m/%Y %H:%M') %></td>
					</tr>
					<tr>
						<td><b>Create At</b></td>
						<td><%= @admin.created_at.strftime('%d/%m/%Y %H:%M') %></td>
					</tr>
				</table>
				<div class="form-actions">
					<%= link_to 'Edit', edit_admins_admin_path(@admin), :class => 'btn btn-secondary' %>
					<%= link_to 'Destroy', admins_admin_path(@admin), :data => { :confirm => 'Are you sure?' }, :method => :delete, :class => 'btn btn-danger' %>
					<%= link_to 'View All', admins_admins_path, :class => 'btn btn-light' %>
				</div>
			</div>
		</div>
	</div>
</div>